name 'elk'
maintainer 'Zan Loy'
maintainer_email 'zan.loy@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures elk'
long_description 'Installs/Configures elk'
version '0.1.0'
chef_version '>= 12.14' if respond_to?(:chef_version)
issues_url 'https://github.com/zanloy/chef-elk/issues'
source_url 'https://github.com/zanloy/chef-elk'

depends 'java'
depends 'elasticsearch'
depends 'simple-logstash'
depends 'kibana5'
depends 'nginx'
